[package]
name = "mc68000"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mc68000-cli"
path = "src/main.rs"

[[bin]]
name = "mc68000-gui"
path = "src/main_gui.rs"

[dependencies]
eframe = "0.32.3"
egui = "0.32.3"
env_logger = "0.11.8"
