name: CI

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Install system dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libxrandr-dev libxi-dev libgl1-mesa-dev
        
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Check with Clippy
      run: cargo clippy --all-targets --all-features
      
    - name: Build CLI version
      run: cargo build --bin mc68000 --verbose
      
    - name: Build GUI version
      run: cargo build --bin mc68000-gui --verbose
      
    - name: Install cargo-tarpaulin (for coverage)
      run: cargo install cargo-tarpaulin
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Run tests with coverage
      run: cargo tarpaulin --out xml --output-dir coverage/ --skip-clean
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: coverage/cobertura.xml
        fail_ci_if_error: false
      
    - name: Run CLI binary (smoke test)
      run: |
        cargo run --bin mc68000 --quiet -- --help || true
        echo "CLI binary smoke test completed"